spring.application.name=quantity-measurement-app
#
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#
#spring.jpa.hibernate.ddl-auto=update
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console



spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=quantity
spring.datasource.password=patil@2406
 
# JPA (optional)
spring.jpa.hibernate.ddl-auto=update
server.port=8080
